__LOGGER_NAME = "qiniu-s3-mcp"


def get_logger_name() -> str:
    return __LOGGER_NAME


CONFIG_ENV_KEY_ACCESS_KEY = "QINIU_ACCESS_KEY"
CONFIG_ENV_KEY_SECRET_KEY = "QINIU_SECRET_KEY"
CONFIG_ENV_KEY_ENDPOINT_URL = "QINIU_ENDPOINT_URL"
CONFIG_ENV_KEY_REGION_NAME = "QINIU_REGION_NAME"
CONFIG_ENV_KEY_BUCKETS = "QINIU_BUCKETS"
